version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/postgresClient/container/:/var/lib/postgres/data
    ports:
      - 5432:5432
