services:
  lms-prod:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    depends_on:
      - postgres
    ports:
      - 3000:3000
  postgres:
    build:
      context: .
      dockerfile: ./postgres.Dockerfile
    volumes:
      - ./src/postgresClient/container/:/var/lib/postgres/data
