version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine3.19
    volumes:
      - ./src/postgresClient/postgres/:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
