name: initial workflow
on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    name: lint job 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install dependencies
        working-directory: ./server
        run: npm ci
        run: npx eslint ./src
