name: initial workflow
on:
  push:
    branches:
      - main

jobs:
  tester:
    runs-on: ubuntu-latest
    name: test job
    steps:
      - name: step one
        run: |
          echo "the varibales are"
          echo $GITHUB_REF
          echo $GITHUB_ACTION
          echo $GITHUB_JOB
          echo $GITHUB_ACTOR
          echo $GITHUB_WORKSPACE
