name: initial workflow
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  push:
    branches-ignore:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    environment: deployment
    name: lint job
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - run: npm run lint
      - name: create .env file
        run: |
          echo "${{ secrets.DEPLOYMENT_SECRETS }}" > .env
      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.0
        with:
          compose-file: "./server/docker-compose.dev.yml"
          down-flags: "--volumes --rmi all"
      - run: npm run test
        env:
          CI: true,
      - name: build the app
        run: tsc
